### ISSUE TITLE
[FEATURE] Take profit targets

### ISSUE THREAD

**Issue by Poilaucul** [Effanuel/BitMEX-scaled-orders#11]
Hello,

Would it be possible to add the ability to set multiple take profit targets with a stop limit order when price reaches deepest entry order?
Something like:
![image](https://user-images.githubusercontent.com/2638123/84307975-0ce79300-ab5e-11ea-9a9a-51c3cb00517c.png)

Or new boxes for Take Profit #1, Take Profit #2, Take Profit #N and so forth.
With a "+" button to add Take Profit Boxes.

Regards,

**Comment by Effanuel** [comment]
That's a really cool idea. My initial plan for that was to actually create a separate container, where you could setup order placing and profit taking in the same place. I'll take this into account for the future, since I have work and some other stuff. Thanks a lot for reminding me.

**Comment by Poilaucul** [comment]
@Effanuel did you have any time to look into it?

**Comment by Effanuel** [comment]
@Poilaucul You can test it on `Profit-Targets` branch. Just pull the branch, and clean install with the usual steps. It's just a first iteration, wanted to know your opinion on it.

**Comment by Effanuel** [comment]
Released.
