### ISSUE TITLE
Issues with npm run build

### ISSUE THREAD

**Issue by wayjeeair** [Effanuel/BitMEX-scaled-orders#12]
When sending the command npm run build an error message is produced.

sh: SET: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! api@1.7.1 build: `SET NODE_ENV=production && cd ../client && npm run build && cd ../api`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the api@1.7.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by sf52crypto** [comment]
Are you trying to build on Linux? Set is a windows command. I had made a
fork for Linux that works.

**Comment by wayjeeair** [comment]
Im building on mac osx. I will try the linux fork

**Comment by wayjeeair** [comment]
switched over to the linux fork, worked perfectly fine for me.
