### ISSUE TITLE
[FEATURE] Auto-fill with current price

### ISSUE THREAD

**Issue by Poilaucul** [Effanuel/BitMEX-scaled-orders#16]
Hello,

When going long:
Auto fill the "Lower Price" box with [current price + 1 (or a user defined amount)]
If "Higher Price" price could be set at the same time at [current price + [user] defined percentage] would be nice.

And the other way around when going short.

Regards,

**Comment by Poilaucul** [comment]
@Effanuel Is this something hard to implement?

**Comment by ingnelson** [comment]
@Poilaucul you should explain a little better and with examples and screenshots , because I do not understand . Are you talking about scale order feature ?

**Comment by Poilaucul** [comment]
Simply something similarto this mockup :
![Mockup](https://imgur.com/yntq0MI.png)


Where Stop-Loss = Current price + Stop-Loss Offset

**Comment by ingnelson** [comment]
@Poilaucul this feature would be better that it can works with all the other features and not only with scale orders.

This feature that you say would be better if it has a take _profit offset box_ too.

so if the master implement this feature should be outside the scale order , this way this can works for the other orders types too.

I think the program has to grab the _Entry Price_ and then we can type the _stop-loss offset_  using a **stop market** and the _take profit offset_  using l_imit order with post only_

**Comment by Poilaucul** [comment]
@ingnelson this is the take profit implementation I was proposing https://github.com/Effanuel/BitMEX-scaled-orders/issues/11

**Comment by Effanuel** [comment]
I don't know how useful this feature would be. I would have to think about it. I feel like it complicates the flow too much.

**Comment by ingnelson** [comment]
@Effanuel the program do not have _stop-loss_ and _take-profit_ feature , it is very important have a feature to place the _stop-loss_ and _take_profit_ , because this way we do not need to keep using the Bitmex Website.

**Comment by Effanuel** [comment]
I realized that this specific feature I am not going to implement. I just released Open Orders Container #28 that has the ability to setup profit targets, and also added copying to clipboard on price click in Ticker Prices Container
