### ISSUE TITLE
Automatically quantity needed or contracts needed(enhancement)

### ISSUE THREAD

**Issue by ingnelson** [Effanuel/BitMEX-scaled-orders#27]
@Effanuel could you create a checked dot or checked box on the "trailing order feature "  and "market order feature"  , when it is checked do this  : 
the program automatically calculate the "quantity needed " at the current price to have a better entry and more close to the current price.

Example : I have 10,000 contracts for example on the wallet

I executed a buy order  using 100 contracts at the price  $1000.

Then the price move down to 999.5 so my unrealised PNL is negative, but if I execute a new order 200 contracts at the current price 999.5 my new current  entry is 999.5 and so on ....

Calculate manually the exact quantity needed to us it is too slow compared to the computer;  imagine if we used 3736 contracts and then the price moves against us 6 points , calculate the exact Quantity needed at the current prices takes time , time the market do not allow us. The fast we react the better the entry.

What I am trying to say is that most of the times we are on a trade but maybe we entered late and the prices goes against us but we have enough contracts to keep buying to have a better entry , but it takes time calculate the quantity value needed at the current prices to have a better entry.

Like you know the price move very fast and when we try to calcule the quantity needed on excel the prices just go away.
It is more easy the program automatically caculate and we just click  or press the buy button .

I think for this enhancement the program  has to display the "entry price" , "contracts executed "  , the "unrealised PNL" ( dollars ) , and the "quantity needed at the current price"  .  I suggest to add information feature below the bitcoin price , this is just a information feature.

I will wait your answer.

**Comment by Effanuel** [comment]
Hey, I can't really understand what you mean. 
> Then the price move down to 999.5 so my unrealised PNL is negative, but if I execute a new order 200 contracts at the current price 999.5 my new current entry is 999.5 and so on ....

If you executed a new order to get your entry price down to 999.5, it would just mean you adjusted your liquidity. It doesn't mean your current entry is 999.5. It is actually going to be $1000 with 100 contracts, and $999.5 with 200 contracts. BitMEX just displays it as one price because its more simple. 


Also,  I don't get this part. Quantity needed for what?
> "quantity needed " at the current price to have a better entry and more close to the current price.

**Comment by ingnelson** [comment]
@Effanuel the quantity needed to have the entry price near the current prices when the prices goes against you.

Here is another example :
Create a buy order with 100 contracts at the price 10,000.
Imagine the price moves down to 9995 and you add another  buy order with 30,000 contracts  with this new buy order your entry price would be 9995 and not 10,000.

This is similar what the scale order do with "Average price", but only using 1 order .

**Comment by ingnelson** [comment]
@Effanuel i propose this enhancement , because one of the best crypto traders on twitter ( @salsatekila ) , he most of the time catch the bottom or the top and he always say the frase : keep clicking ! , so I beging to think: how it is possible he most of the time catch the top or the bottom ? There are 2 answer : 
1) he use scale order feature and he find the best stop because he is a good trader.
2) when he catch the dip is because he keep clicking ( adding contracts ) while the price is going against him . so this method may works more easy if the program automatically calcule the contra needed to keep his " entry price" near the current price .

Salsatekila did 3956 % profit or ROE in the bybit competition ! That is crazy ! 

Here the screenshot : 
![20201122_085950](https://user-images.githubusercontent.com/6626845/99907248-61f90a80-2ca1-11eb-9df8-c56115d17e8b.jpg)

**Comment by Effanuel** [comment]
But he is not really catching the bottom/tops. Its just that his biggest order happens to be at the bottom/top, which undermines the other smaller ones. Also, I don't think he uses market orders to get his fills, only for actually pushing the markets.

This kind of feature would bring emotions into your trading too much. On average, if you don't know where you want to buy/sell, you shouldn't buy/sell.

If you say that he gets his orders filled at the top or bottoms, open up a chart and look at the levels, that indicate those bottoms and tops.

**Comment by ingnelson** [comment]
@Effanuel yes , just like you said , first he use small orders then the biggest orders are at the bottom/top.

We can begin with a small order and if goes against my entry order  and my risk management is OK and I have the enough 
 contracts to excetute another order to have a better entry price would be OK. 

So that depends the risk management for every trader and the contracts he feels OK to trade.

**Comment by Effanuel** [comment]
I am closing this, since this kind of feature will lose you more more than bring an actual benefit.
